### ISSUE TITLE
04-30 14:19:17 ERROR driver.util :: Database connection error

### ISSUE THREAD

**Issue by Nageshyr** [swisscom-bigdata/metabase-teradata-driver#6]
Hello - I am trying to connect metabase to Teradata w/metabase-teradata-driver.

I was able to select 'Teradata' in the Add data drop down option -

Then, after entering the credentials - I get an error - which just says 'An error occurred'

Not able to figure out what the error is - anyway to resolve this...

Thanks
![metabase-error](https://user-images.githubusercontent.com/20627783/79149883-d677dc80-7d95-11ea-94c2-ecafc26f157c.png)

**Comment by tsadauskas** [comment]
Hi @Nageshyr.
Have you tried looking at the logs?

**Comment by Nageshyr** [comment]
![image](https://user-images.githubusercontent.com/20627783/80747981-3f7b8600-8af2-11ea-81da-ee75bc308291.png)

I have all my .jar file in /plugins

I have my CLASSPATH set to /plugins dir 

I am able to see Teradata as a selective database.

I am entering all my database credentials - when I try to save, I am getting an error

'No suitable driver found....

![image](https://user-images.githubusercontent.com/20627783/80748438-ecee9980-8af2-11ea-887e-612b080df8a9.png)

**Comment by rawyler** [comment]
You are using Metabase v0.35.3. The latest metabase-teradata-driver release is 1.0.0-metabase-v0.34.1-teradata-jdbc-16.20 and therefore compatible with v0.34.x Metabase versions. v0.34 metabase-teradata-driver releases are not compatible with Metabase v0.35 releases.

**Comment by Nageshyr** [comment]
Ok - Is there a way to download older version v0.34 of Metabase? Thx

**Comment by rawyler** [comment]
You can find earlier releases here: https://github.com/metabase/metabase/releases

I hope I will find some time to do the upgrade this month

**Comment by Nageshyr** [comment]
Yep - Just found - I will try that...Thank you.

**Comment by tsadauskas** [comment]
Closing issue - it's a simple version mismatch.

**Comment by Nageshyr** [comment]
> Closing issue - it's a simple version mismatch.

Yep - Simple mismatch!!! - I am able to connect - Thank you guys...
