### ISSUE TITLE
Not working for Metabase 0.38

### ISSUE THREAD

**Issue by zeehasham** [swisscom-bigdata/metabase-teradata-driver#9]
I am getting the error with Metabase 0,38 latest version

No suitable driver found for jdbc:teradata://SERVER/DATABASE=BODS_BASE_VW,DBS_PORT=1025,CHARSET=UTF8,TMODE=ANSI,ENCRYPTDATA=ON,FINALIZE_AUTO_CLOSE=ON,LOB_SUPPORT=OFF

Do you know when the new teradata-metabase driver will be release for Metabase 0.38?

Thanks

**Comment by robstoll** [comment]
@zeehasham we released a version for metabase 0.38, try it out and give feedback. Closing this issue for now
